# application.yml
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4
      temperature: 0.7
      max-tokens: 1000
      timeout: 30s
      log-requests: true
      log-responses: true

# Application-specific settings
app:
  guardrails:
    input:
      max-length: 1000
      rate-limit:
        enabled: true
        max-requests-per-minute: 10
    output:
      max-retries: 3
      retry-delay: 1s

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}